# Generated by Django 5.1.5 on 2025-02-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=100)),
                ('module_code', models.CharField(max_length=10)),
                ('classwork1', models.IntegerField()),
                ('classwork2', models.IntegerField()),
                ('classwork3', models.IntegerField()),
            ],
        ),
    ]
